// Qué se busca en Wikimedia Commons para cada producto del catálogo.
//
// Buscar por el nombre común en español no sirve: "Durazno" devuelve fotos de una
// ciudad de Uruguay y ningún durazno, y "Tomate" devuelve una banda de rock. El
// nombre científico, en cambio, es unívoco en Commons. Donde la especie sola
// traería la planta, la flor o una lámina botánica, se agrega una palabra en
// inglés que empuja el resultado hacia el producto comestible tal como se vende
// en la verdulería; las variedades que comparten especie se separan por color o
// tipo, porque si no todas terminarían con la misma foto.

export const PRODUCE_IMAGE_QUERIES: Record<string, string> = {
  // Frutas
  "anana": "Ananas comosus pineapple fruit",
  "arandanos": "Vaccinium corymbosum blueberries fruit",
  "banana": "Musa acuminata banana fruit",
  "caqui": "Diospyros kaki persimmon fruit",
  "cereza": "Prunus avium cherry fruit",
  "chirimoya": "Annona cherimola cherimoya fruit",
  "ciruela": "Prunus domestica plum fruit",
  "damasco": "Prunus armeniaca apricot fruit",
  "durazno": "Prunus persica peach fruit",
  "frambuesa": "Rubus idaeus raspberry fruit",
  "frutilla": "Fragaria ananassa strawberry fruit",
  "granada": "Punica granatum pomegranate fruit",
  "higo": "Ficus carica fig fruit",
  "kiwi": "Actinidia deliciosa kiwifruit fruit",
  "lima": "Citrus aurantiifolia lime fruit",
  "limon": "Citrus limon lemon fruit",
  "mamon": "Carica papaya papaya fruit",
  "mandarina": "Citrus reticulata mandarin fruit",
  "mango": "Mangifera indica mango fruit",
  "manzana-roja": "red apple fruit",
  "manzana-verde": "Granny Smith apple",
  "maracuya": "Passiflora edulis passion fruit",
  "melon-amarillo": "yellow canary melon fruit",
  "melon-blanco": "honeydew melon fruit",
  "membrillo": "Cydonia oblonga quince fruit",
  "mora": "Rubus fruticosus blackberry fruit",
  "naranja": "Citrus sinensis orange fruit",
  "naranja-de-jugo": "Valencia orange fruit",
  "nispero": "Eriobotrya japonica loquat fruit",
  "pelon": "nectarine fruit",
  "pera": "Pyrus communis pear fruit",
  "pomelo": "Citrus paradisi grapefruit fruit",
  "sandia": "Citrullus lanatus watermelon fruit",
  "sandia-baby": "mini watermelon fruit",
  "tuna": "Opuntia ficus-indica prickly pear fruit",
  "uvas-negras": "black table grapes",
  "uvas-rosadas": "red table grapes",
  "uvas-verdes": "green table grapes",

  // Verduras
  "acelga": "Beta vulgaris cicla Swiss chard leaves",
  "achicoria": "Cichorium intybus chicory leaves",
  "aji-picante": "Capsicum chili peppers fruit",
  "ajo": "Allium sativum garlic bulb",
  "alcaucil": "Cynara scolymus artichoke head",
  "anco": "Cucurbita moschata butternut squash",
  "apio": "Apium graveolens celery stalks",
  "arveja": "Pisum sativum green peas pods",
  "batata": "sweet potato Ipomoea batatas tubers",
  "berenjena": "Solanum melongena eggplant fruit",
  "berro": "Nasturtium officinale watercress leaves",
  "boniato": "purple sweet potato tubers",
  "brocoli": "Brassica oleracea italica broccoli head",
  "brotes-de-alfalfa": "alfalfa sprouts",
  "brotes-de-rabanito": "radish sprouts",
  "brotes-de-soja": "mung bean sprouts",
  "cabutia": "Cucurbita moschata calabaza squash",
  "cardo": "Cynara cardunculus cardoon stalks",
  "cebolla": "Allium cepa onion bulb",
  "cebolla-morada": "red onion bulb",
  "cebollita-de-verdeo": "spring onion scallions bunch",
  "champinones": "Agaricus bisporus white button mushrooms",
  "chaucha": "Phaseolus vulgaris green beans pods",
  "choclo": "sweet corn cob",
  "coliflor": "Brassica oleracea botrytis cauliflower head",
  "echalote": "shallot bulbs",
  "endivia": "Belgian endive witloof",
  "escarola": "Cichorium endivia escarole leaves",
  "esparrago": "Asparagus officinalis spears",
  "espinaca": "Spinacia oleracea spinach leaves",
  "girgolas": "Pleurotus ostreatus oyster mushroom",
  "haba": "Vicia faba broad beans pods",
  "hinojo": "Foeniculum vulgare fennel bulb",
  "jengibre": "Zingiber officinale ginger rhizome",
  "kale": "Brassica oleracea acephala kale leaves",
  "lechuga-capuchina": "batavia crisphead lettuce",
  "lechuga-criolla": "green leaf lettuce",
  "lechuga-francesa": "romaine cos lettuce",
  "lechuga-mantecosa": "butterhead lettuce",
  "lechuga-morada": "red leaf lettuce",
  "morron-amarillo": "yellow bell pepper",
  "morron-rojo": "red bell pepper",
  "morron-verde": "green bell pepper",
  "nabo": "Brassica rapa turnip root",
  "palta": "Persea americana avocado fruit",
  "papa-blanca": "white potato tubers",
  "papa-lavada": "washed potatoes tubers",
  "papa-negra": "russet potato tubers",
  "papines-andinos": "Andean potato tubers",
  "pepino": "Cucumis sativus cucumber fruit",
  "portobellos": "portobello mushrooms",
  "puerro": "Allium ampeloprasum leek",
  "rabanito": "Raphanus sativus radish bunch",
  "radicchio": "radicchio red chicory",
  "radicheta": "young chicory leaves",
  "remolacha": "Beta vulgaris beetroot root",
  "repollitos-de-bruselas": "Brussels sprouts",
  "repollo-blanco": "white cabbage head",
  "repollo-colorado": "red cabbage head",
  "rucula": "Eruca vesicaria rocket arugula leaves",
  "tomate": "Solanum lycopersicum fruit",
  "tomate-cherry": "cherry tomato",
  "tomate-perita": "Roma tomato",
  "zanahoria": "Daucus carota carrot root",
  "zapallito": "Cucurbita maxima zapallito round squash",
  "zapallo-plomo": "Cucurbita maxima whole squash",
  "zucchini": "Cucurbita pepo zucchini courgette",

  // Aromáticas
  "albahaca": "Ocimum basilicum",
  "ciboulette": "Allium schoenoprasum chives",
  "cilantro": "Coriandrum sativum",
  "eneldo": "Anethum graveolens",
  "estragon": "Artemisia dracunculus",
  "laurel": "Laurus nobilis leaves",
  "menta": "Mentha spicata",
  "oregano": "Origanum vulgare",
  "perejil": "Petroselinum crispum",
  "romero": "Salvia rosmarinus",
  "salvia": "Salvia officinalis",
  "tomillo": "Thymus vulgaris",

  // Huevos
  "huevos-por-docena": "chicken eggs carton dozen",
  "huevos-media-docena": "half dozen chicken eggs box",
  "maple-de-huevos-blanco": "white chicken eggs tray",
  "maple-de-huevos-color": "brown chicken eggs tray",
  "huevos-de-codorniz": "quail eggs",
};
